version: "3.8"

services:
  api:
    build: .
    container_name: crm_api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    # jangan pakai go run lagi
    command: ["./api-crm"]
